server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    name: localhost
    url: jdbc:mysql://localhost:3306/jdbc?serverTimezone=GMT%2B8
    username: root
    password: youpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.model